services:
  itelectric-database:
    container_name: itelectric-database
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      -  itelectric-dbdata:/data/db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - itelectric-network

volumes:
  itelectric-dbdata:

networks:
  itelectric-network:
    driver: bridge