services:
  itelectric-database:
    container_name: itelectric-database
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      - itelectric-dbdata:/data/db
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=itelectric
    networks:
      - itelectric-network

  keycloak-server:
    container_name: keycloak_server
    image: quay.io/keycloak/keycloak:26.0.7
    ports:
      - "8081:8080"
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://itelectric-database:5432/keycloak
      - KC_DB_URL_HOST=itelectric-database
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_HOSTNAME=localhost
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    depends_on:
      - itelectric-database
    networks:
      - itelectric-network
    command: start --http-enabled=true

  itelectric-backend:
    build:
      context: .
    container_name: itelectric-backend
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - itelectric-database
      - keycloak-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      ## DATABASE CONFIGURATION
      - SPRING_DATASOURCE_URL=jdbc:postgresql://itelectric-database:5432/itelectric
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_SHOW_SQL=false
    command: mvn spring-boot:run
    networks:
      - itelectric-network

volumes:
  itelectric-dbdata:

networks:
  itelectric-network:
    driver: bridge