services:
  itelectric-database:
    container_name: itelectric-database
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      -  itelectric-dbdata:/data/db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - itelectric-network

  itelectric-backend:
    build:
     context: .
    container_name: itelectric-backend
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - itelectric-database
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      ## DATABASE CONFIGURATION
      - SPRING_DATASOURCE_URL=jdbc:postgresql://itelectric-database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_SHOW_SQL=false
    command: mvn spring-boot:run
    networks:
      - itelectric-network

volumes:
  itelectric-dbdata:

networks:
  itelectric-network:
    driver: bridge